name: cognitive_complexity_analyzer
description: A starting point for Dart libraries or applications.
version: 0.1.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  analyzer: any
  test: any

dev_dependencies:
  lints: ^4.0.0

bin:
  # Name of your executable file (without the .dart extension)
  cognitive_complexity_analyzer: # This should match your file name